/**
 * StudEx Nexus Dashboard — Enhanced Overview Page
 * File: studex-frontend/app/dashboard/page.tsx
 * 
 * Adds: Fulfillment crisis banner, inventory alerts, privacy toggle
 * Design: Cream-gold palette (#FFF8F0 bg, #D4A017 gold)
 * 
 * Generated by: Perplexity Computer | 2026-06-01
 */

"use client";

import { useState, useEffect } from "react";

// ── Types ──────────────────────────────────────────────────────
interface UnfulfilledOrder {
  id: string;
  name: string;
  customerInitials: string;
  amount: number;
  daysWaiting: number;
}

interface InventoryAlert {
  product: string;
  stock: number;
  severity: "critical" | "low" | "ok";
}

// ── Known Crisis Data (from Perplexity Computer live pull 2026-06-01) ──
const UNFULFILLED_ORDERS: UnfulfilledOrder[] = [
  { id: "1941", name: "#1941", customerInitials: "H.M.", amount: 552, daysWaiting: 5 },
  { id: "1940", name: "#1940", customerInitials: "L.N.", amount: 3220, daysWaiting: 20 },
  { id: "1939", name: "#1939", customerInitials: "I.H.", amount: 1610, daysWaiting: 23 },
  { id: "1938", name: "#1938", customerInitials: "S.S.", amount: 2932, daysWaiting: 34 },
  { id: "1937", name: "#1937", customerInitials: "M.P.", amount: 3220, daysWaiting: 37 },
  { id: "1936", name: "#1936", customerInitials: "N.M.", amount: 1552, daysWaiting: 39 },
  { id: "1935", name: "#1935", customerInitials: "N.H.", amount: 4542, daysWaiting: 44 },
  { id: "1932", name: "#1932", customerInitials: "T.S.", amount: 3858, daysWaiting: 58 },
  { id: "1922", name: "#1922", customerInitials: "W.K.", amount: 86250, daysWaiting: 85 },
  { id: "1930", name: "#1930", customerInitials: "F.T.", amount: 11097, daysWaiting: 61 },
];

const INVENTORY_ALERTS: InventoryAlert[] = [
  { product: "Wagyu Burger Patties", stock: -248, severity: "critical" },
  { product: "Tomahawk 1kg", stock: -209, severity: "critical" },
  { product: "Tomahawk 2kg", stock: -71, severity: "critical" },
  { product: "Luxury Wagyu Biltong 1kg", stock: -218, severity: "critical" },
  { product: "Luxury Wagyu Biltong 500g", stock: -81, severity: "critical" },
  { product: "VIP Large Wagyu Box", stock: -15, severity: "critical" },
  { product: "Fire & Feast Box", stock: -50, severity: "critical" },
  { product: "Ankole Ribeye 1kg", stock: 7, severity: "low" },
];

// ── Privacy Hook ───────────────────────────────────────────────
function usePrivacy() {
  const [masked, setMasked] = useState(false);
  const mask = (val: number | string) =>
    masked ? "••••••" : typeof val === "number" ? `R${val.toLocaleString()}` : val;
  return { masked, toggle: () => setMasked((m) => !m), mask };
}

// ── Severity Badge ─────────────────────────────────────────────
function DaysBadge({ days }: { days: number }) {
  const color =
    days > 60
      ? "bg-red-100 text-red-700 border-red-300"
      : days > 30
      ? "bg-amber-100 text-amber-700 border-amber-300"
      : "bg-green-100 text-green-700 border-green-300";
  return (
    <span className={`text-xs font-mono px-2 py-0.5 rounded border ${color}`}>
      {days}d
    </span>
  );
}

// ── Main Dashboard ─────────────────────────────────────────────
export default function DashboardPage() {
  const { masked, toggle, mask } = usePrivacy();
  const [showAllOrders, setShowAllOrders] = useState(false);
  const totalOutstanding = UNFULFILLED_ORDERS.reduce((s, o) => s + o.amount, 0);
  const criticalCount = UNFULFILLED_ORDERS.filter((o) => o.daysWaiting > 60).length;
  const displayOrders = showAllOrders ? UNFULFILLED_ORDERS : UNFULFILLED_ORDERS.slice(0, 5);

  return (
    <div className="min-h-screen bg-[#FFF8F0] font-sans">
      {/* Header */}
      <div className="border-b border-[#D4A017]/20 bg-white px-6 py-4 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-[#1A1A1A] tracking-tight">
            STUDEX NEXUS
          </h1>
          <p className="text-xs text-gray-500 font-mono mt-0.5">// Command Centre</p>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-gray-400 font-mono">
            {new Date().toLocaleDateString("en-ZA", {
              weekday: "short", day: "numeric", month: "short"
            })} · SAST
          </span>
          <button
            onClick={toggle}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-mono border transition-all ${
              masked
                ? "bg-[#D4A017] text-white border-[#D4A017]"
                : "bg-white text-gray-600 border-gray-300 hover:border-[#D4A017]"
            }`}
          >
            {masked ? "👁 SHOW" : "🔒 HIDE"}
          </button>
        </div>
      </div>

      <div className="px-6 py-6 max-w-6xl mx-auto space-y-6">
        {/* ── Fulfillment Crisis Banner ── */}
        <div className="bg-red-50 border-2 border-red-400 rounded-xl p-4">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="text-red-600 font-bold text-sm">⚠ CASHCLAW PHASE 0 — FULFILLMENT CRISIS</span>
                <span className="bg-red-600 text-white text-xs font-mono px-2 py-0.5 rounded-full">
                  {criticalCount} CRITICAL
                </span>
              </div>
              <p className="text-sm text-red-700">
                <span className="font-bold">{UNFULFILLED_ORDERS.length} paid orders</span> awaiting fulfillment ·{" "}
                <span className="font-mono font-bold">{mask(totalOutstanding)}</span> outstanding ·{" "}
                Oldest: <span className="font-mono">85 days</span>
              </p>
            </div>
            <a
              href="https://admin.shopify.com/store/studexmeat/orders?fulfillment_status=unfulfilled&financial_status=paid"
              target="_blank"
              rel="noopener noreferrer"
              className="shrink-0 bg-red-600 hover:bg-red-700 text-white text-xs font-semibold px-4 py-2 rounded-lg transition-colors"
            >
              Open Shopify →
            </a>
          </div>

          {/* Order table */}
          <div className="mt-3 overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="text-red-500 font-mono border-b border-red-200">
                  <th className="text-left pb-1 pr-4">Order</th>
                  <th className="text-left pb-1 pr-4">Customer</th>
                  <th className="text-right pb-1 pr-4">Amount</th>
                  <th className="text-right pb-1">Waiting</th>
                </tr>
              </thead>
              <tbody>
                {displayOrders.map((order) => (
                  <tr key={order.id} className="border-b border-red-100 last:border-0">
                    <td className="py-1 pr-4 font-mono text-[#1A1A1A]">{order.name}</td>
                    <td className="py-1 pr-4 text-gray-700">{order.customerInitials}</td>
                    <td className="py-1 pr-4 text-right font-mono font-semibold text-[#1A1A1A]">
                      {mask(order.amount)}
                    </td>
                    <td className="py-1 text-right">
                      <DaysBadge days={order.daysWaiting} />
                    </td>
                  </tr>
                ))}
              </tbody>
              {!showAllOrders && UNFULFILLED_ORDERS.length > 5 && (
                <tfoot>
                  <tr>
                    <td colSpan={4} className="pt-2">
                      <button
                        onClick={() => setShowAllOrders(true)}
                        className="text-red-600 hover:underline text-xs font-mono"
                      >
                        + {UNFULFILLED_ORDERS.length - 5} more orders...
                      </button>
                    </td>
                  </tr>
                </tfoot>
              )}
            </table>
          </div>
        </div>

        {/* ── Stats Row ── */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: "TODAY'S REVENUE", value: 0, sub: "No orders yet" },
            { label: "THIS MONTH", value: 284300, sub: "Jun 2026" },
            { label: "TOTAL ORDERS", value: "925", sub: "All time", noMask: true },
            { label: "UNFULFILLED", value: `${UNFULFILLED_ORDERS.length} ⚠`, sub: "Paid, waiting", noMask: true },
          ].map((stat) => (
            <div key={stat.label} className="bg-white border border-[#D4A017]/20 rounded-xl p-4">
              <p className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-1">
                {stat.label}
              </p>
              <p className="text-2xl font-bold text-[#1A1A1A] font-mono">
                {stat.noMask
                  ? stat.value
                  : masked
                  ? "••••••"
                  : typeof stat.value === "number"
                  ? `R${stat.value.toLocaleString()}`
                  : stat.value}
              </p>
              <p className="text-xs text-gray-400 mt-0.5">{stat.sub}</p>
            </div>
          ))}
        </div>

        {/* ── Inventory Alerts ── */}
        <div className="bg-white border border-amber-300 rounded-xl p-4">
          <h2 className="text-sm font-bold text-[#1A1A1A] mb-3 flex items-center gap-2">
            🔴 INVENTORY ALERTS
            <span className="text-xs font-mono bg-amber-100 text-amber-700 px-2 py-0.5 rounded-full border border-amber-300">
              {INVENTORY_ALERTS.filter((i) => i.severity === "critical").length} products overselling
            </span>
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
            {INVENTORY_ALERTS.map((item) => (
              <div
                key={item.product}
                className={`rounded-lg p-2.5 border ${
                  item.severity === "critical"
                    ? "bg-red-50 border-red-200"
                    : "bg-amber-50 border-amber-200"
                }`}
              >
                <p className="text-xs text-gray-700 leading-tight mb-1">{item.product}</p>
                <p
                  className={`text-lg font-mono font-bold ${
                    item.stock < 0 ? "text-red-600" : "text-amber-600"
                  }`}
                >
                  {item.stock > 0 ? `+${item.stock}` : item.stock}
                </p>
                <p className="text-[10px] text-gray-400 font-mono uppercase">
                  {item.severity === "critical" ? "Overselling" : "Low stock"}
                </p>
              </div>
            ))}
          </div>
          <p className="text-xs text-gray-500 mt-3 font-mono">
            Fix: Shopify Admin → Product → Inventory → uncheck "Continue selling when out of stock"
          </p>
        </div>

        {/* ── Quick Actions ── */}
        <div className="bg-white border border-[#D4A017]/20 rounded-xl p-4">
          <h2 className="text-sm font-bold text-[#1A1A1A] mb-3">QUICK ACTIONS</h2>
          <div className="flex flex-wrap gap-2">
            {[
              { label: "View All Orders", href: "https://admin.shopify.com/store/studexmeat/orders", external: true },
              { label: "Refresh Facebook Token", href: "https://developers.facebook.com/tools/explorer", external: true },
              { label: "Google Ads", href: "https://ads.google.com/aw/campaigns?customerId=2234319068", external: true },
              { label: "GA4 Analytics", href: "https://analytics.google.com/analytics/web/#/p295728486/reports", external: true },
              { label: "Shopify Admin", href: "https://admin.shopify.com/store/studexmeat", external: true },
            ].map((action) => (
              <a
                key={action.label}
                href={action.href}
                target={action.external ? "_blank" : undefined}
                rel={action.external ? "noopener noreferrer" : undefined}
                className="text-xs px-3 py-2 bg-[#FFF8F0] hover:bg-[#D4A017]/10 border border-[#D4A017]/30 hover:border-[#D4A017] text-[#1A1A1A] rounded-lg transition-all font-mono"
              >
                {action.label} {action.external ? "↗" : ""}
              </a>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
