#!/usr/bin/env node
/**
 * StudEx Facebook MCP Server
 * Provides Facebook Page data tools for Claude Code via Model Context Protocol
 * 
 * Surfaces: page insights, posts, engagement, token status
 * Store: studexmeat.myshopify.com | Page ID: 108934711902801
 * 
 * Generated by: Perplexity Computer | 2026-06-01
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  Tool,
} from "@modelcontextprotocol/sdk/types.js";

const FB_PAGE_ID = process.env.FB_PAGE_ID || "108934711902801";
const FB_ACCESS_TOKEN = process.env.META_ACCESS_TOKEN || "";
const FB_API_BASE = "https://graph.facebook.com/v19.0";

async function fbFetch(path: string, params: Record<string, string> = {}) {
  if (!FB_ACCESS_TOKEN) {
    return { error: "META_ACCESS_TOKEN not set. Refresh at developers.facebook.com/tools/explorer" };
  }
  const url = new URL(`${FB_API_BASE}/${path}`);
  url.searchParams.set("access_token", FB_ACCESS_TOKEN);
  Object.entries(params).forEach(([k, v]) => url.searchParams.set(k, v));
  
  try {
    const res = await fetch(url.toString());
    const data = await res.json() as Record<string, unknown>;
    if ((data as any).error) {
      return { error: (data as any).error.message, code: (data as any).error.code };
    }
    return data;
  } catch (err) {
    return { error: String(err) };
  }
}

const TOOLS: Tool[] = [
  {
    name: "get_page_info",
    description: "Get StudEx Meat Facebook Page info: fans, followers, category, verification status",
    inputSchema: { type: "object", properties: {} },
  },
  {
    name: "get_page_insights",
    description: "Get Facebook Page insights: reach, impressions, engagement for last 28 days",
    inputSchema: {
      type: "object",
      properties: {
        period: { type: "string", enum: ["day", "week", "days_28"], default: "days_28" },
      },
    },
  },
  {
    name: "list_posts",
    description: "List recent posts on StudEx Meat Facebook Page with engagement metrics",
    inputSchema: {
      type: "object",
      properties: {
        limit: { type: "number", default: 10, description: "Number of posts (max 25)" },
      },
    },
  },
  {
    name: "get_post_engagement",
    description: "Get detailed engagement for a specific post: likes, comments, shares, reach",
    inputSchema: {
      type: "object",
      properties: {
        post_id: { type: "string", description: "Facebook post ID" },
      },
      required: ["post_id"],
    },
  },
  {
    name: "check_token_status",
    description: "Check if the META_ACCESS_TOKEN is valid and what permissions it has",
    inputSchema: { type: "object", properties: {} },
  },
  {
    name: "get_ad_account_summary",
    description: "Get Facebook Ad Account summary for act_560666565541381: spend, impressions, reach",
    inputSchema: {
      type: "object",
      properties: {
        date_preset: {
          type: "string",
          enum: ["today", "yesterday", "last_7d", "last_30d", "this_month"],
          default: "last_30d",
        },
      },
    },
  },
];

const server = new Server(
  { name: "studex-facebook-mcp", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args = {} } = request.params;

  try {
    let result: unknown;

    switch (name) {
      case "get_page_info":
        result = await fbFetch(`${FB_PAGE_ID}`, {
          fields: "name,fan_count,followers_count,category,verification_status,about,website",
        });
        break;

      case "get_page_insights": {
        const period = (args.period as string) || "days_28";
        result = await fbFetch(`${FB_PAGE_ID}/insights`, {
          metric: "page_impressions,page_reach,page_engaged_users,page_fans",
          period,
        });
        break;
      }

      case "list_posts": {
        const limit = Math.min((args.limit as number) || 10, 25);
        result = await fbFetch(`${FB_PAGE_ID}/posts`, {
          fields: "id,message,created_time,likes.summary(true),comments.summary(true),shares",
          limit: String(limit),
        });
        break;
      }

      case "get_post_engagement":
        result = await fbFetch(`${args.post_id}`, {
          fields: "likes.summary(true),comments.summary(true),shares,reach,impressions",
        });
        break;

      case "check_token_status":
        result = await fbFetch("me", {
          fields: "id,name",
        });
        // Also check token debug
        const debugUrl = new URL(`${FB_API_BASE}/debug_token`);
        debugUrl.searchParams.set("input_token", FB_ACCESS_TOKEN);
        debugUrl.searchParams.set("access_token", FB_ACCESS_TOKEN);
        const debug = await fetch(debugUrl.toString()).then((r) => r.json());
        result = { me: result, token_debug: debug };
        break;

      case "get_ad_account_summary": {
        const date_preset = (args.date_preset as string) || "last_30d";
        result = await fbFetch("act_560666565541381/insights", {
          fields: "spend,impressions,reach,clicks,cpm,cpc",
          date_preset,
        });
        break;
      }

      default:
        throw new Error(`Unknown tool: ${name}`);
    }

    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
    };
  } catch (err) {
    return {
      content: [{ type: "text", text: `Error: ${err}` }],
      isError: true,
    };
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("StudEx Facebook MCP Server running on stdio");
}

main().catch(console.error);
