#!/usr/bin/env bash
# Clone Foreman (eve software factory) as a SIBLING repo. Do not vendor it
# into Stud-Ex-Global-Markets- (Node 24 + pnpm + eve would fight this app).
# Run on Mac Mini after vercel login. Does not deploy by itself.
set -euo pipefail

DEST="${FOREMAN_DIR:-$HOME/src/studex-foreman}"
SRC="${FOREMAN_TEMPLATE:-https://github.com/vercel-labs/eve-software-factory-template.git}"
FACTORY_REPO="${FACTORY_REPO:-TumeloRamaphosa/Stud-Ex-Global-Markets-}"
FACTORY_LABEL="${FACTORY_LABEL:-factory}"
FACTORY_BRANCH_PREFIX="${FACTORY_BRANCH_PREFIX:-factory/}"

mkdir -p "$(dirname "$DEST")"
if [[ -d "$DEST/.git" ]]; then
  echo "Foreman already cloned at $DEST"
  git -C "$DEST" fetch --depth 1 origin
else
  git clone --depth 1 "$SRC" "$DEST"
fi

ENV_FILE="$DEST/.env.local"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# Generated by StudEx bootstrap-foreman.sh. Connectors come from vercel env pull.
FACTORY_REPO=$FACTORY_REPO
FACTORY_LABEL=$FACTORY_LABEL
FACTORY_BRANCH_PREFIX=$FACTORY_BRANCH_PREFIX
# GITHUB_CONNECTOR=
# LINEAR_CONNECTOR=
EOF
  echo "Wrote $ENV_FILE"
else
  echo "Left existing $ENV_FILE"
fi

cat <<EOF

Next (on the Mac Mini, after vercel login):

  cd $DEST
  vercel link          # new project: studex-foreman
  vercel env pull      # fills GITHUB_CONNECTOR / LINEAR_CONNECTOR
  pnpm install         # Node 24 — do this on Mini, not the full MacBook
  pnpm dev             # local TUI; /model once
  eve deploy           # production Foreman

Intake: label a GitHub issue on $FACTORY_REPO with '$FACTORY_LABEL'.
Until that deploy exists, run stations from this repo:

  ops/agent-stack/factory/run-line.sh classifier
  ops/agent-stack/factory/dispatch-cursor.sh   # implementer, --go only with quota

Do not copy $DEST onto the MacBook disk.
EOF
